### PR TITLE
Add new functions for manipulating the environment

### PR DESCRIPTION
**Pull request by mjcarroll**
This adds functions for using collections with the environment.  It allows for conveniently retreiving and setting the environment variables via a map, rather than individually.

This also adds a clearenv and printenv for completeness.

### CODE REVIEW

**Comment by iche033** [comment]
Is the idea to eventually deprecate the env functions in gz-common and use these instead?

**Comment by mjcarroll** [comment]
> Is the idea to eventually deprecate the env functions in gz-common and use these instead?

The gz-common ones are now just forwarding to the other env functions here.  I added them because we have packages that we want env functionality in that don't depend on gz-common (eg sdformat).

**Comment by azeey** [comment]
A couple of tests are failing on windows.

**Review by azeey — APPROVED** [review]
LGTM!

**Pull request merged**
