### PR TITLE
Fix logging source location

### LINKED ISSUE #147: Empty file/line when logging
## Environment
* OS Version: Ubuntu 24.04 -->
* Source or binary build? Source using the `gz-utils3` branch (aae0d8c3e920eaf5b0e04664d4087bc1b2ca6f12)

## Description

* Expected behavior: When logging a message:
```
logger.RawLogger().trace("trace\n");
```
we should see:
```
(2024-09-22 19:48:25.019) [trace] [main.cc:32] trace
```
* Actual behavior: Instead, we see:
```
(2024-09-22 20:28:20.394) [trace] [:] trace
```

## Steps to reproduce

1. Compile the `main.cc` example under `examples/log` and run it.

### PR DESCRIPTION
**Pull request by caguero**
# 🦟 Bug fix

Fixes #147 

According to the [spdlog notes about location flags](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#source-location-flags), when using source location flags it's necessary to define this compiler flag:

```
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
```

and then, use the `SPDLOG_LOGGER_XXX()` macros. This patch adds the `#define` and updates the example.

Without this patch:
```
(2024-09-26 19:53:49.435) [info] [:] info
(2024-09-26 19:53:49.435) [warning] [:] warn
(2024-09-26 19:53:49.435) [error] [:] error
(2024-09-26 19:53:49.435) [critical] [:] critical
```
With this patch:
```
(2024-09-26 19:52:52.543) [info] [main.cc:34] info
(2024-09-26 19:52:52.543) [warning] [main.cc:35] warn
(2024-09-26 19:52:52.543) [error] [main.cc:36] error
(2024-09-26 19:52:52.543) [critical] [main.cc:37] critical
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by azeey** [comment]
I'm surprised that the source location works for `gz*` macros (fix in https://github.com/gazebosim/gz-utils/pull/144), but not when using spdlog directly. Are we doing something different for our macros?

**Review by iche033 — APPROVED** [review]
tested and confirmed that the example now prints out source file name and line no.

**Comment by iche033** [comment]
windows caught a compile error:

```
C:\J\workspace\gz_utils-pr-win\ws\gz-utils\log\src\Logger_TEST.cc(146,35): error C2664: 'void gz::utils::log::v3::Logger::SetLogDestination(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [C:\J\workspace\gz_utils-pr-win\ws\build\gz-utils3\log\src\UNIT_Logger_TEST.vcxproj]
```

**Comment by iche033** [comment]
> windows caught a compile error:
> 
> ```
> C:\J\workspace\gz_utils-pr-win\ws\gz-utils\log\src\Logger_TEST.cc(146,35): error C2664: 'void gz::utils::log::v3::Logger::SetLogDestination(const std::string &)': cannot convert argument 1 from 'std::filesystem::path' to 'const std::string &' [C:\J\workspace\gz_utils-pr-win\ws\build\gz-utils3\log\src\UNIT_Logger_TEST.vcxproj]
> ```

testing fix: [b94745f](https://github.com/gazebosim/gz-utils/pull/150/commits/b94745f288b8add73ae0963614a75b6a9d0159e6)

**Review by iche033 — APPROVED** [review]

**Pull request merged**
