### PR TITLE
Report test results from GitHub Actions

### PR DESCRIPTION
**Pull request by mjcarroll**
This introduces a `composite_jammy` action, which allows for all the arguments to be forwarded to our standard Jammy CI (https://github.com/gazebo-tooling/action-gz-ci/tree/composite_jammy).  At the end, it aggregates the test failures and reports them as part of the Github Action results

### CODE REVIEW

**Comment by scpeters** [comment]
looks cool!

**Comment by mjcarroll** [comment]
Consider using: https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/ to modify the base action, rather than having to update each workflow.

**Comment by mjcarroll** [comment]
CC: @azeey and @scpeters I think this is ready for another look.  It still has an intentionally-failing test to be removed before merging, but is now making use of the composite action discussed above.

**Review by azeey — APPROVED** [review]
This looks great! I guess there's nothing to merge here right?

**Comment by mjcarroll** [comment]
> This looks great! I guess there's nothing to merge here right?

Currently, there are new branches in the action that need to be used.  So there is a `jammy` branch, and in order to get the reporting, you need to use `composite_jammy`.  Likewise for `focal`.

I suppose we could invert the logic (making the `jammy` branch contain the composite action) and then all the repos would get it as a no-op?

**Comment by azeey** [comment]
> I suppose we could invert the logic (making the jammy branch contain the composite action) and then all the repos would get it as a no-op?

Yeah, I thought we were enabling this everywhere. Would there be a problem if we do?

**Comment by mjcarroll** [comment]
> Yeah, I thought we were enabling this everywhere. Would there be a problem if we do?

Shouldn't be an issue, just wanted to make sure before I changed actions everywhere

**Pull request closed without merging**
