### PR TITLE
Merge: 2 -> main

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port gz-utils2 to main

Branch comparison: https://github.com/gazebosim/gz-utils/compare/main...gz-utils2

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by mjcarroll** [comment]
If possible, I have #105, #106, #107, and #108 ready to be reviewed that we could get in before this.

**Comment by iche033** [comment]
ok yeah this can wait

**Comment by mjcarroll** [comment]
Actually, CI looks good, we can also just do another forward port later.

**Review by mjcarroll — APPROVED** [review]

**Comment by iche033** [comment]
ok merging

**Pull request merged**
